
export const dependencyData = {
  "arithmetic": [],
  "elementaryalgebra": [],
  "linearalgebra": [],
  "vectorspacetheory": ["linearalgebra"],
  "matrixtheory": ["linearalgebra"],
  "precalculus": [],
  "calculus": ["precalculus"],
  "mathematicalanalysis": ["calculus"],
  "ordinarydifferentialequations": ["calculus", "mathematicalanalysis"],
  "settheory": [],
  "logic&prooftheory": [],
  "combinatorics": ["settheory"],
  "graphtheory": ["combinatorics"],
  "euclideangeometry": [],
  "analyticgeometry": ["euclideangeometry"],
  "coordinatesystems": ["analyticgeometry"],
  "abstractalgebra": ["linearalgebra", "elementaryalgebra", "logic&prooftheory"],
  "advancedsettheory": ["settheory", "logic&prooftheory"],
  "differentialequations": ["ordinarydifferentialequations", "calculus", "mathematicalanalysis"],
  "complexanalysis": ["calculus", "mathematicalanalysis"],
  "fourieranalysis": ["calculus", "mathematicalanalysis"],
  "calculusofvariations": ["calculus", "mathematicalanalysis"],
  "probabilitytheory": ["calculus", "mathematicalanalysis"],
  "differentialgeometry": ["calculus", "analyticgeometry", "vectorspacetheory"],
  "grouptheory": ["abstractalgebra"],
  "ringtheory": ["abstractalgebra"],
  "functionalanalysis": ["mathematicalanalysis", "linearalgebra"],
  "topology": ["advancedsettheory", "analyticgeometry"],
  "riemanniangeometry": ["differentialgeometry", "linearalgebra", "mathematicalanalysis"],
  "manifoldtheory": ["topology", "differentialgeometry"],
  "categorytheory": ["advancedsettheory", "logic&prooftheory"],
  "modeltheory": ["logic&prooftheory", "advancedsettheory"],
  "computability&recursiontheory": ["logic&prooftheory", "arithmetic"],
  "measuretheory": ["mathematicalanalysis", "probabilitytheory"],
  "fieldtheory": ["ringtheory"],
  "moduletheory": ["grouptheory", "linearalgebra"],
  "liegroups": ["grouptheory", "differentialgeometry"],
  "algebraictopology": ["topology", "categorytheory"],
  "algebraicgeometry": ["abstractalgebra", "topology", "manifoldtheory"],
  "differentialtopology": ["manifoldtheory", "differentialgeometry"],
  "informationtheory": ["probabilitytheory", "linearalgebra", "logic&prooftheory"],
  "statisticalmechanics": ["probabilitytheory", "differentialequations"],
  "stochasticprocesses": ["probabilitytheory", "functionalanalysis"],
  "chaos&complexity": ["differentialequations"],
  "liealgebras": ["liegroups", "abstractalgebra"],
  "representation-readyalgebra": ["moduletheory", "liealgebras"],
  "quantummechanics": ["functionalanalysis", "linearalgebra", "differentialgeometry"],
  "generalrelativity": ["riemanniangeometry", "differentialgeometry"],
  "gaugetheory": ["liegroups", "differentialgeometry", "functionalanalysis"],
  "probabilitystructures": ["measuretheory", "probabilitytheory"],
  "calabi–yaugeometry": ["riemanniangeometry", "algebraicgeometry", "differentialgeometry"],
  "homologicalalgebra": ["moduletheory", "categorytheory"],
  "representationtheory": ["liealgebras", "moduletheory"],
  "quantumfieldtheory": ["liealgebras", "functionalanalysis", "differentialgeometry"],
  "sheaf&cohomologytheory": ["algebraicgeometry", "homologicalalgebra"],
  "topostheory": ["categorytheory", "logic&prooftheory", "topology"],
  "riemannhypothesis": ["complexanalysis", "algebraicgeometry", "numbertheory"],
  "stringtheory": ["quantumfieldtheory", "algebraicgeometry", "differentialgeometry"],
  "numbertheory": ["fieldtheory", "complexanalysis", "algebraicgeometry"]
};
export const difficultyColor = {
  //basic
  "arithmetic": "#77DD77",
  "elementaryalgebra": "#77DD77",
  "linearalgebra": "#77DD77",
  "vectorspacetheory": "#77DD77",
  "matrixtheory": "#77DD77",
  "precalculus": "#77DD77",
  "calculus": "#77DD77",
  "settheory": "#77DD77",
  "logic&prooftheory": "#77DD77",
  "combinatorics": "#77DD77",
  "graphtheory": "#77DD77",
  "euclideangeometry": "#77DD77",
  "analyticgeometry": "#77DD77",
  "coordinatesystems": "#77DD77",

  //intermediate
  "mathematicalanalysis": "#FFD966",
  "ordinarydifferentialequations": "#FFD966",
  "advancedsettheory": "#FFD966",
  "differentialequations": "#FFD966",
  "complexanalysis": "#FFD966",
  "fourieranalysis": "#FFD966",
  "calculusofvariations": "#FFD966",
  "probabilitytheory": "#FFD966",
  "abstractalgebra": "#FFD966",
  "topology": "#FFD966",
  "functionalanalysis": "#FFD966",
  "riemanniangeometry": "#FFD966",
  "manifoldtheory": "#FFD966",
  "grouptheory": "#FFD966",
  "ringtheory": "#FFD966",
  "categorytheory": "#FFD966",
  "modeltheory": "#FFD966",
  "measuretheory": "#FFD966",
  "differentialgeometry": "#FFD966",
  "differentialtopology": "#FFD966",
  "moduletheory": "#FFD966",
  "fieldtheory": "#FFD966",

  //advanced
  "liegroups": "#FF6961",
  "liealgebras": "#FF6961",
  "representation-readyalgebra": "#FF6961",
  "representationtheory": "#FF6961",
  "homologicalalgebra": "#FF6961",
  "algebraictopology": "#FF6961",
  "algebraicgeometry": "#FF6961",
  "sheaf&cohomologytheory": "#FF6961",
  "topostheory": "#FF6961",
  "quantummechanics": "#FF6961",
  "generalrelativity": "#FF6961",
  "gaugetheory": "#FF6961",
  "quantumfieldtheory": "#FF6961",
  "stringtheory": "#FF6961",
  "calabi–yaugeometry": "#FF6961",
  "riemannhypothesis": "#FF6961",
  "chaos&complexity": "#FF6961",
  "stochasticprocesses": "#FF6961",
  "informationtheory": "#FF6961",
  "statisticalmechanics": "#FF6961",
  "numbertheory": "#FF6961",
  "computability&recursiontheory": "#FF6961",
  "probabilitystructures": "#FF6961"
};
